collectconfig:
  sotfwareInfoUrl:
  apppkgInfoUrl:
  projectsInfoUrl:
  openEulerOsVersionInfoUrl:
  dockerHubOpeneulerOsVersionInfoUrl:
server:
  port: 8080


gitee:
  fork:
    accessToken:
    owner:
    email:
    name:




  pr:

    rpmPrTitle:
    rpmIssueNum:
    appPrTitle:
    appIssueNum:
    changelog:


softwareconfig:
  appkgschedule: 0 0 1 * * ?
  appkgOsSchedule: 0 0 3 * * ?
  rpmSchedule: 0 0 3 * * ?
