collectconfig:
  apppkgInfoUrl:
  projectsInfoUrl:
  apppkgDetailUrl:
  openEulerOsVersionInfoUrl:
  dockerHubOpeneulerOsVersionInfoUrl:
  dockerHubOpeneulerHomepage:
  dockerHubOpeneulerAuthorization:



softwareconfig:
  appkgschedule: 0 0 1 * * ?
  appkgOsSchedule: 0 0 3 * * ?
  rpmSchedule: 0 0 3 * * ?



softcenter:
  application:
    repoInfo:
      owner:
      repo:

    forkInfo:
      accessToken:
      owner:
      email:
      name:
      password:
      scope:
      clientId:
      clientSecret:

    prInfo:
      prTitle:
      issueNum:
    mailInfo:
      host:
      from:
      senderUsername:
      senderPassword:
  rpm:
    repoInfo:
      owner:
      repo:

    forkInfo:
      accessToken:
      owner:
      email:
      name:
      password:
      scope:
      clientId:
      clientSecret:

    prInfo:
      prTitle:
      issueNum:
      changelog:

server:
  port: 8080